included:
  - POILog
  - POILogTests

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 80
  error: 150

identifier_name:
  min_length: 1

disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_comma
