name: POILog
options:
  bundleIdPrefix: com.poilogger
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: 1
    DEVELOPMENT_TEAM: U8A4E46MT9
    CODE_SIGN_STYLE: Automatic
  configs:
    Debug:
      ENABLE_TESTABILITY: true

targets:
  POILog:
    type: application
    platform: iOS
    sources:
      - POILog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.poilogger.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: true
    dependencies:
      - sdk: MapKit.framework
      - sdk: CoreLocation.framework

  POILogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - POILogTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: POILog
